shared:
  api_key: 123
development:
  secret_key_base: <your_secret_key_base>
test:
  secret_key_base: <your_secret_key_base>
  twitter_api_key: "<your_api_key>"
  twitter_api_secret: "<your_api_secret_key>"
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>